[package]
name = "actix-web-hw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
base64 = "0.21.2"
rusqlite = "0.29.0"
serde = { version = "1.0.171", features = ["derive"] }
